apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ec2s.omerap12.com
spec:
  group: omerap12.com
  names:
    kind: EC2
    plural: ec2s
  claimNames:
    kind: EC2Claim
    plural: ec2claims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  ec2type:
                    type: string
                    description: "The type of the EC2 instance - can be cheap, memory, cpu, gpu or storage optimized"
                    default: cheap
                  operatingSystem:
                    type: string
                    description: "Can be linux(AL), windows or ubuntu" 
                    default: linux
                  region:
                    type: string
                    description: "The region in which the EC2 instance will be created"
                    default: us-east-1
                  subnetId:
                    type: string
                    description: "The subnet in which the EC2 instance will be created"
                  associatePublicIpAddress: 
                    type: boolean
                    description: "Whether the EC2 instance should have a public IP address"
                    default: false