apiVersion: omerap12.com/v1alpha1
kind: EC2
metadata:
  name: ec2-light
  annotations:
    creator: crossplane
    author: omerap12
spec:
  compositionSelector:
    matchLabels:
      provider: aws
  parameters:
    ec2type: cheap
    operatingSystem: linux
    region: us-east-1
